amethyst: cd mathbot && python entrypoint.py PARAMETERS.env '{"shards": {"mine": [0, 1, 2]}}'
emerald:  cd mathbot && python entrypoint.py PARAMETERS.env '{"shards": {"mine": [3, 4, 5]}}'
saphire:  cd mathbot && python entrypoint.py PARAMETERS.env '{"shards": {"mine": [6, 7, 8]}}'
topaz:    cd mathbot && python entrypoint.py PARAMETERS.env '{"shards": {"mine": [9, 10, 11]}}'
opal:     cd mathbot && python entrypoint.py PARAMETERS.env '{"shards": {"mine": [12, 13, 14]}}'
