amethyst: cd mathbot && python bot.py PARAMETERS.env '{"shards": {"mine": [0, 1]}}'
emerald:  cd mathbot && python bot.py PARAMETERS.env '{"shards": {"mine": [2]}}'
citrine:  cd mathbot && python bot.py PARAMETERS.env '{"shards": {"mine": [3]}}'
saphire:  cd mathbot && python bot.py PARAMETERS.env '{"shards": {"mine": [4, 5]}}'
topaz:    cd mathbot && python bot.py PARAMETERS.env '{"shards": {"mine": [6, 7]}}'
